package uy.gub.agesic.itramites.bruto.web.ws.linea;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * La numeración de los enumerados está basada en el modelo de trazas definido por Unit
 *
 * This class was generated by Apache CXF 3.1.12
 * 2022-03-15T14:39:49.732-03:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/lineaService", name = "CapturaLineaSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface CapturaLineaSOAP {

    @WebMethod(action = "http://ws.web.bruto.itramites.agesic.gub.uy/lineaService/ping")
    @RequestWrapper(localName = "ping", targetNamespace = "http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/lineaService", className = "uy.gub.agesic.itramites.bruto.web.ws.linea.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/lineaService", className = "uy.gub.agesic.itramites.bruto.web.ws.linea.PingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String ping();

    @WebMethod(action = "http://ws.web.bruto.itramites.agesic.gub.uy/lineaService/persist")
    @RequestWrapper(localName = "persist", targetNamespace = "http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/lineaService", className = "uy.gub.agesic.itramites.bruto.web.ws.linea.Persist")
    @ResponseWrapper(localName = "persistResponse", targetNamespace = "http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/lineaService", className = "uy.gub.agesic.itramites.bruto.web.ws.linea.PersistResponse")
    @WebResult(name = "return", targetNamespace = "")
    public uy.gub.agesic.itramites.bruto.web.ws.linea.ResponseDTO persist(
        @WebParam(name = "traza", targetNamespace = "")
        uy.gub.agesic.itramites.bruto.web.ws.linea.LineaDTO traza
    );
}
