package uy.gub.agesic.itramites.bruto.web.ws.linea;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2022-03-15T14:39:49.786-03:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "lineaService", 
                  wsdlLocation = "../../../../../../../../LineaServicesV2.wsdl",
                  targetNamespace = "http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/lineaService") 
public class LineaService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/lineaService", "lineaService");
    public final static QName CapturaLineaSOAPPort = new QName("http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/lineaService", "CapturaLineaSOAPPort");
    static {
        URL url = null;
        try {
        	URL baseUrl;
    		baseUrl = uy.gub.agesic.itramites.bruto.web.ws.linea.LineaService.class.getResource(".");		
            url = new URL("../../../../../../../../LineaServicesV2.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LineaService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "../../../../../../../../LineaServicesV2.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LineaService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LineaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LineaService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public LineaService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LineaService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LineaService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CapturaLineaSOAP
     */
    @WebEndpoint(name = "CapturaLineaSOAPPort")
    public CapturaLineaSOAP getCapturaLineaSOAPPort() {
        return super.getPort(CapturaLineaSOAPPort, CapturaLineaSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CapturaLineaSOAP
     */
    @WebEndpoint(name = "CapturaLineaSOAPPort")
    public CapturaLineaSOAP getCapturaLineaSOAPPort(WebServiceFeature... features) {
        return super.getPort(CapturaLineaSOAPPort, CapturaLineaSOAP.class, features);
    }

}
