#  Nombre del cliente
#  Nombre del cliente
#  Sistema de Gesti\u00f3n
#  Desarrollado por Sofis Solutions

ERROR_GENERAL = Se produjo un error
GUARDADO_CORRECTO = El elemento se guard\u00f3 correctamente
AGREGADO_CORRECTO = El elemento se agreg\u00f3 correctamente
CAMBIO_PASSWORD_CORRECTO = La contrase\u00f1a se cambi\u00f3 correctamente
ELIMINADO_CORRECTO = El elemento se elimin\u00f3 correctamente
ENVIADO_CORRECTO = El elemento se envi\u00f3 correctamente

TITULO_VAC = T\u00edtulo vac\u00edo
FECHA_APROBACION_INVALIDA = Fecha de aprobaci\u00f3n inv\u00e1lida
ANIO_INICIO_VAC = Per\u00edodo Desde no puede estar vac\u00edo
ANIO_FIN_VAC = Per\u00edodo Hasta no puede estar vac\u00edo
OPERACION_VAC = Operaci\u00f3n vac\u00eda
PAIS_EMISOR_VAC = Pa\u00eds emisor vac\u00edo
TIPO_DOCUMENTO_USUARIO_VAC = Tipo de documento vac\u00edo
NUMERO_DOCUMENTO_VAC = N\u00famero de documento vac\u00edo
DOCUMENTO_ADJUNTO_VAC = Documento a cargar vac\u00edo
TIPO_DOCUMENTO_ADJUNTO_VAC = Tipo de documento a cargar vac\u00edo
TIPO_PARTICIPACION_DESTINO_VAC = Tipo de participaci\u00f3n de destino vac\u00edo
CONTRASENIA_ACTUAL_VAC = Contrase\u00f1a actual vac\u00eda
CONTRASENIA_NUEVA_VAC = Contrase\u00f1a nueva vac\u00eda
CONFIRMACION_CONTRASENIA_VAC = Confirmaci\u00f3n de contrase\u00f1a vac\u00eda

PREGUNTA_VAC = Pregunta vac\u00eda
REGION_VAC = Regi\u00f3n vac\u00eda
NOM_VAC = Nombre no puede estar vac\u00edo
COD_VAC = C\u00f3digo vac\u00edo
DES_VAC = Descripci\u00f3n vac\u00eda
CARGO_VAC = Cargo vac\u00edo
APE_VAC = Apellido vac\u00edo
EMAIL_VAC = Email vac\u00edo
TEXTO_VAC = Texto vac\u00edo
ROL_VAC = Rol vac\u00edo
USUARIO_VAC = Usuario vac\u00edo
GRUPO_VAC = Grupo vac\u00edo
NOM_APE_VAC = Nombre y apellido vac\u00edo

GUARDADO_CORRECTO_PROYECTO = El proyecto se guard\u00f3 correctamente
CONFIGURACION_NO_CARGADA = No se pudo cargar configuraci\u00f3n:
OPERACION_VACIA = Debe seleccionar una operaci\u00f3n
CANTIDAD_MINIMA_CARACTERES_ESPECIALES = Cantidad m\u00ednima de caracteres especiales
CONTRASENIA_INCLUYE_USUARIO = La contrase\u00f1a incluye el c\u00f3digo de usuario
CONTRASENIAS_NO_COINCIDEN = La nueva contrase\u00f1a no coincide con la confirmaci\u00f3n
CONTRASENIA_ACTUAL_INVALIDA = La contrase\u00f1a actual no es v\u00e1lida
DIAS_PARA_CADUCIDAD_VAC = Cantidad de d\u00edas para la caducidad de la contrase\u00f1a vac\u00eda
CANTIDAD_INTETOS_FALLICOS_VAC = Cantidad de intentos fallidos vac\u00eda
LARGO_MINIMO_VAC = Largo m\u00ednimo de contrase\u00f1a vac\u00edo
CANTIDAD_MINIMA_CARACTERES_ESPECIALES_VAC = Cantidad m\u00ednima de caracteres especiales vac\u00eda.
CANTIDAD_MINIMA_DIGITOS_VAC = Cantidad m\u00ednima de digitos vac\u00eda
CANTIDAD_MINIMA_LETRAS_MAYUSCULAS_VAC = Cantidad m\u00ednima de letras may\u00fasculas vac\u00eda
DIAS_PARA_CADUCIDAD_INVALIDO = Cantidad de d\u00edas para la caducidad de la contrase\u00f1a inv\u00e1lida
CANTIDAD_INTETOS_FALLICOS_INVALIDA = Cantidad de intentos fallidos inv\u00e1lida
LARGO_MINIMO_INVALIDO = Largo m\u00ednimo de contrase\u00f1a inv\u00e1lido
CANTIDAD_MINIMA_CARACTERES_ESPECIALES_INVALIDA = Cantidad m\u00ednima de caracteres especiales inv\u00e1lida
CANTIDAD_MINIMA_DIGITOS_INVALIDA = Cantidad m\u00ednima de digitos inv\u00e1lida
CANTIDAD_MINIMA_LETRAS_MAYUSCULAS_INVALIDA = Cantidad m\u00ednima de letras may\u00fasculas inv\u00e1lida

CORREO_ENVIADO = Correo electr\u00f3nico enviado satisfactoriamente
EMAIL_NO_COINCIDE = El email ingresado no coincide con el registrado
USUARIO_NO_BLOQUEADO = El usuario no tiene la cuenta bloqueada
CODIGO_USUARIO_INEXISTENTE = C\u00f3digo de usuario inexistente
ERROR_USUARIO_O_EMAIL_INEXISTENTE = C\u00f3digo o correo inexistentes

CUENTA_BLOQUEADA = Cuenta bloqueada
SUPERO_INTENTOS_FALLIDOS = Su cuenta ha sido bloqueada. Por favor contacte al Administrador del Sistema
USUARIO_CONTRASENIA_INVALIDOS = Contrase\u00f1a incorrecta
USUARIO_CREDENCIALES_INVALIDAS = C\u00f3digo de usuario o contrase\u00f1a incorrectos
USUARIO_DESHABILITADO = Usuario deshabilitado

CODIGO_REPETIDO = Ya hay un elemento con este c\u00f3digo
CODIGO_INVALIDO = C\u00f3digo inv\u00e1lido

SIN_PERMISO_OPERACION = No tiene permiso para esta operaci\u00f3n
DOCUMENTO_NO_SOPORTADO = Documento no soportado

LARGO_CARGO_CONTACTO = El cargo del contacto no puede superar los 45 caracteres
LARGO_NOMBRE_CONTACTO = El nombre del contacto no puede superar los 100 caracteres
LARGO_APELLIDO_CONTACTO = El apellido del contacto no puede superar los 100 caracteres
LARGO_TELEFONO_CONTACTO = El tel\u00e9fono del contacto no puede superar los 45 caracteres
LARGO_NOM_APE_100 = El nombre y apellido del usuario no puede superar los 100 caracteres
LARGO_EMAIL_CONTACTO = El email del contacto no puede superar los 45 caracteres
LARGO_TEXTO_NOTA = El texto de la nota no puede superar los 1000 caracteres
LARGO_NOMBRE_DOCUMENTO = El nombre del documento no puede superar los 250 caracteres
LARGO_CODIGO_PAIS = El c\u00f3digo del pa\u00eds no puede superar los 2 caracteres
LARGO_EXPLICACION_AYUDA = La explicaci\u00f3n de la ayuda no puede superar los 65535 caracteres
LARGO_PREGUNTA = La pregunta no puede superar los 255 caracteres
LARGO_NOMBRE_USUARIO = El nombre del usuario no puede superar los 255 caracteres
LARGO_APELLIDO_USUARIO = El apellido del usuario no puede superar los 255 caracteres
LARGO_NUMERO_DOCUMENTO_USUARIO = El n\u00famero de documento del usuario no puede superar los 45 caracteres
LARGO_TIPO_DOCUMENTO_USUARIO = El tipo de documento del usuario no puede superar los 45 caracteres
LARGO_EMAIL_USUARIO = El email del usuario no puede superar los 255 caracteres
LARGO_TELEFONO_USUARIO = El tel\u00e9fono del usuario no puede superar los 45 caracteres
LARGO_CELULAR_USUARIO = El celular del usuario no puede superar los 45 caracteres
LARGO_CONTRASENIA_USUARIO = La contrase\u00f1a del usuario no puede superar los 255 caracteres
LARGO_CODIGO_USUARIO = El c\u00f3digo del usuario no puede superar los 45 caracteres
LARGO_CODIGO_5 = El c\u00f3digo no puede superar los 5 caracteres
LARGO_CODIGO_10 = El c\u00f3digo no puede superar los 10 caracteres
LARGO_CODIGO_25 = El c\u00f3digo no puede superar los 25 caracteres
LARGO_CODIGO_45 = El c\u00f3digo no puede superar los 45 caracteres
LARGO_NOMBRE_45 = El nombre no puede superar los 45 caracteres
LARGO_NOMBRE_255 = El nombre no puede superar los 255 caracteres
LARGO_APELLIDO_255 = El apellido no puede superar los 255 caracteres
LARGO_DESCRIPCION_255 = La descripci\u00f3n no puede superar los 255 caracteres
LARGO_DESCRIPCION_1000 = La descripci\u00f3n no puede superar los 1000 caracteres
LARGO_VALOR_255 = El valor no puede superar los 255 caracteres
LARGO_VALOR_2000 = El valor no puede superar los 2000 caracteres
USUARIO_DUPLICADO= Ya existe un usuario con ese c\u00f3digo
OPERACION_EXISTENTE_EN_ROL=Esa operaci\u00f3n ya existe en el rol
PREGUNTA_DUPLICADO=Esa pregunta ya est\u00e1 asignada
RESPUESTA_CAPTCHA_INCORRECTA = Respuesta dada no es correcta
RESPUESTA_CAPTCHA_INEXISTENTE = Ingrese respuesta a la pregunta secreta
CODIGO_USUARIO_VAC =  Ingrese c\u00f3digo de usuario
    
GUARDAR_USUARIO_CONSTRAINT_VIOLATION = Ya existe un usuario con mismo c\u00f3digo o documento de identidad en el sistema
CONSTRAINT_VIOLATION = La operaci\u00f3n no respeta las restricciones del sistema. Esto sucede generalmente al duplicar datos que deben ser \u00fanicos o al borrar datos que est\u00e1n referenciados
ACCESO_DENEGADO = No tiene permisos para realizar dicha acci\u00f3n

ARCHIVO_VACIO = El archivo no puede ser vac\u00edo
ESTADO_VACIO = El estado no puede estar vac\u00edo
ASUNTO_VACIO = El asunto no puede ser vac\u00edo
LARGO_ASUNTO_255 = El asunto no puede superar los 255 caracteres
CUERPO_VACIO = El cuerpo no puede ser vac\u00edo
LARGO_CUERPO_4000 = El cuerpo no puede superar los 4000 caracteres
FECHA_VACIA = La fecha no puede ser vac\u00eda
JUSTIFICACION_VACIA = La justificaci\u00f3n no puede ser vac\u00eda
LARGO_JUSTIFICACION_2000 = La justificaci\u00f3n no puede superar los 2000 caracteres
NUMERO_DEPOSITO_VACIO = El n\u00famero de dep\u00f3sito no puede ser vac\u00edo
LARGO_NUMERO_DEPOSITO_255 = El n\u00famero de dep\u00f3sito no puede superar los 255 caracteres
MONTO_DEBE_SER_NUMERO_POSITIVO = El monto debe ser un n\u00famero positivo
NUMERO_INTERVENCION_VACIO = El n\u00famero de intervenci\u00f3n no puede ser vac\u00edo
LARGO_NUMERO_INTERVENCION_255 = El n\u00famero de intervenci\u00f3n no puede sueperar los 255 caracteres
PROYECTOS_DEBEN_PERTENECER_A_MISMA_INSTITUCION = Los proyectos deben pertenecer a la misma instituci\u00f3n
CONFIGURACION_NO_CARGADA = Configuraci\u00f3n no cargada
BENEFACTOR_VACIO = El benefactor no puede ser vac\u00edo
LARGO_ACTIVIDADES_2000 = Las actividades no pueden superar los 2000 caracteres
RESULTADOS_VACIO = Los resultados no pueden ser vac\u00edos
LARGO_RESULTADOS_2000 = Los resultados no pueden superar los 2000 caracteres
LARGO_OBSERVACIONES_2000 = Las observaciones no pueden superar los 2000 caracteres
CONTRAPARTE_NOMBRE_VACIO = El nombre de contraparte no puede ser vac\u00edo
LARGO_CONTRAPARTE_NOMBRE_255 = El nombre de la contraparte no puede superar los 255 caracteres
CONTRAPARTE_APELLIDO_VACIO = El apellido de la contraparte no puede ser vac\u00edo
LARGO_CONTRAPARTE_APELLIDO_255 = El apellido de la contraparte no puede superar los 255 caracteres
CONTRAPARTE_DOCUMENTO_IDENTIDAD_VACIO = El documento de identidad de la contraparte no puede ser vac\u00edo
DOCUMENTO_IDENTIDAD_INVALIDO = El documento de identidad no es v\u00e1lido
PROYECTOS_VACIO = Debe seleccionar al menos un proyecto
TIPO_VACIO = El tipo no puede ser vac\u00edo
SOLO_SE_PUEDE_GUARDAR_TOPE_DE_ANIO_ACTUAL = Solo se puede guardar el tope del a\u00f1o actual
RUT_VACIO = El rut no puede ser vac\u00edo
RUT_INVALIDO = El rut no es v\u00e1lido
RAZON_SOCIAL_VACIA = La raz\u00f3n social no puede ser vac\u00eda
LARGO_RAZON_SOCIAL_255 = La raz\u00f3n social no puede superar los 255 caracteres
CLASFICACION_VACIA = La clasificaci\u00f3n no puede ser vac\u00eda
LARGO_CLASIFICACION_255 = La clasificaci\u00f3n no puede superar los 255 caracteres
LARGO_JUSTIFICACION_1000 = La justificaci\u00f3n no puede superar los 1000 caracteres
DIRECCION_VACIA = La direcci\u00f3n no puede ser vac\u00eda
LARGO_DIRECCION_255 = La direcci\u00f3n no puede superar los 255 caracteres
TELEFONO_VACIO = El tel\u00e9fono no puede ser vac\u00edo
LARGO_TELEFONO_50 = El tel\u00e9fono no puede superar los 50 caracteres
LARGO_FAX_50 = El fax no puede superar los 50 caracteres
LARGO_EMAIL_255 = El email no puede superar los 255 caracteres
LARGO_NUMERO_TESORERIA_40 = El n\u00famero de tesorer\u00eda no puede superar los 40 caracteres
DEPARTAMENTO_VACIO = El departamento no puede ser vac\u00edo
EMAIL_INVALIDO = El email no es v\u00e1lido
ERROR_SECCION_IMPORT_VACIO = El archivo est\u00e1 vac\u00edo
ERROR_FECHA_IMPORT_VACIO = La fecha de importaci\u00f3n est\u00e1 vac\u00eda
IMPORTACION_CORRECTA = La importaci\u00f3n de datos concluy\u00f3 correctamente
ERROR_PERIODO_INFERIOR_2000 = El per\u00edodo debe ser mayor al a\u00f1o 2000
ERROR_PERIODO_DESDE_MAYOR_HASTA = Per\u00edodo Desde debe ser menor o igual al Per\u00eddo Hasta
ERROR_LARGO_CODIGO_20 = El c\u00f3digo no puede superar los 20 caracteres
ERROR_LARGO_NOMBRE_100 = El nombre no puede superar los 100 caracteres
SIGLA_VACIA = Sigla vac\u00eda
SIGLA_20 = La sigla no puede superar los 20 caracteres
VIGENCIA_DESDE_VACIA = Fecha de inicio de vigencia vac\u00eda
VIGENCIA_HASTA_VACIA = Fecha fin de vigencia vac\u00eda
VIGENCIA_HASTA_ANTERIOR = La fecha de inicio es posterior a la fecha de finalizaci\u00f3n
fechaInvalida = Fecha inv\u00e1lida
ACTUALIZACION_CAT_CORRECTO= Se han actualizado los cat\u00e1logos correctamente
ERROR_ARCHIVO_PARSEO = La plantilla csv no se puede parsear
ERROR_RUTA_ARCH_IMP = No se encuentra configurada la ruta del archivo
ERROR_ARCH_IMP = No se encuentra configurado el nombre del archivo a importar

CONTRASENIA_VACIA = No se ha podido asignar una contrase\u00f1a al usuario, intentelo de nuevo
ERROR_ORGANISMO_VACIO = Debe seleccionar un organismo
ERROR_ENVIO_MAIL = No se ha podido crear el usuario, fallo el env\u00edo de la contrase\u00f1a v\u00eda correo electr\u00f3nico.
ERROR_NOCHECK_ADMIN = Debe chequear la casilla Administrador para asignar este nuevo organismo al usuario.