RUTA_ARCHIVOS = C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\templatesGenerador
NOMBRE_ENTIDAD = plantilla_entidad.txt
NOMBRE_FACADE = plantillaSessionBeanFacade.txt
NOMBRE_CLASE_VALIDACION=plantillaValidation.java
NOMBRE_MANAGED_BEAN = plantillaManagedBean.txt
NOMBRE_PAGINA = plantillaPaginaPrivada.txt
NOMBRE_FRAGMENTO = plantillaFragmento.txt
NOMBRE_ETIQUETAS = plantillaEtiquetas.txt
NOMBRE_LAZY_MODEL = plantillaLazyModel.txt
NOMBRE_CREATE_SCRIPT = plantillaCrearTabla.txt

RUTA_SALIDA_ENTIDAD = C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-entities\\src\\main\\java\\uy\\com\\sofis\\entities\\
RUTA_SALIDA_FACADE = C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-ejb\\src\\main\\java\\uy\\com\\sofis\\business\\services\\
RUTA_SALIDA_VALIDACION=C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-ejb\\src\\main\\java\\uy\\com\\sofis\\business\\validaciones\\
RUTA_SALIDA_MANAGED_BEAN = C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-web\\src\\main\\java\\uy\\com\\sofis\\web\\mb\\
RUTA_SALIDA_PAGINA =C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-web\\src\\main\\webapp\\paginasPrivadas\\
RUTA_SALIDA_FRAGMENTO = C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-web\\src\\main\\webapp\\fragmentos\\
RUTA_CREATE_SCRIPT=C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-documentacion\\src\\com\\sql\s\cripts
    
    
RUTA_CONSTANTES_AYUDA=C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-web\\src\\main\\java\\uy\\com\\sofis\\web\\constantes\\ConstantesAyuda.java
RUTA_CONSTANTES_AYUDA_NUEVO=C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-web\\src\\main\\java\\uy\\com\\sofis\\web\\constantes\\ConstantesAyudaNuevo.java
    
RUTA_ETIQUETAS = C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-web\\src\\main\\resources\\com\\sofis\\presentacion\\mensajes\\etiquetas.properties
RUTA_MENU_MB = C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-web\\src\\main\\java\\uy\\com\\sofis\\web\\mb\\MenuView.java
RUTA_MENU_MB_NUEVO = C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-web\\src\\main\\java\\uy\\com\\sofis\\web\\mb\\MenuViewNuevo.java
RUTA_FACES_CONFIG = C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-web\\src\\main\\webapp\\WEB-INF\\faces-config.xml
RUTA_FACES_CONFIG_NUEVO = C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-web\\src\\main\\webapp\\WEB-INF\\faces-configNuevo.xml
RUTA_PERSISTENCE=C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-ejb\\src\\main\\resources\\META-INF\\persistence.xml
RUTA_PERSISTENCE_NUEVO=C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-ejb\\src\\main\\resources\\META-INF\\persistenceNuevo.xml
RUTA_SALIDA_LAZY_MODEL = C:\\Users\\USUARIO\\Desktop\\Fabricio\\linea-base\\linea-base-code\\linea-base-web\\src\\main\\java\\uy\\com\\sofis\\web\\lazymodels\\


GENERATION_TYPE = 0