package uy.gub.agesic.itramites.bruto.web.ws.cabezal;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2022-03-09T12:48:32.089-03:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "cabezalService", 
                  wsdlLocation = "../../../../../../../../CabezalServiceV2.wsdl",
                  targetNamespace = "http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/cabezalService") 
public class CabezalService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/cabezalService", "cabezalService");
    public final static QName CapturaCabezalSOAPPort = new QName("http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/cabezalService", "CapturaCabezalSOAPPort");
    static {
    	URL url = null;
    	try {
    		URL baseUrl;
    		baseUrl = uy.gub.agesic.itramites.bruto.web.ws.cabezal.CabezalService.class.getResource(".");
    		url = new URL(baseUrl, "../../../../../../../../CabezalServiceV2.wsdl");
			
		} catch (MalformedURLException e) {
			 java.util.logging.Logger.getLogger(CabezalService.class.getName())
			 		.log(java.util.logging.Level.INFO,
			 				"Can not initialize the default wsdl from {0}", "../../../../../../../../CabezalServiceV2.wsdl");
		}   
        WSDL_LOCATION = url;
    }

    public CabezalService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CabezalService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CabezalService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CabezalService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CabezalService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CabezalService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CapturaCabezalSOAP
     */
    @WebEndpoint(name = "CapturaCabezalSOAPPort")
    public CapturaCabezalSOAP getCapturaCabezalSOAPPort() {
        return super.getPort(CapturaCabezalSOAPPort, CapturaCabezalSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CapturaCabezalSOAP
     */
    @WebEndpoint(name = "CapturaCabezalSOAPPort")
    public CapturaCabezalSOAP getCapturaCabezalSOAPPort(WebServiceFeature... features) {
        return super.getPort(CapturaCabezalSOAPPort, CapturaCabezalSOAP.class, features);
    }

}
