package uy.gub.agesic.itramites.bruto.web.ws.cabezal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * La numeración de los enumerados está basada en el modelo de trazas definido por Unit
 *
 * This class was generated by Apache CXF 2.4.6
 * 2022-03-09T12:48:32.060-03:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/cabezalService", name = "CapturaCabezalSOAP")
@XmlSeeAlso({ObjectFactory.class})
public interface CapturaCabezalSOAP {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "persist", targetNamespace = "http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/cabezalService", className = "uy.gub.agesic.itramites.bruto.web.ws.cabezal.Persist")
    @WebMethod(action = "http://ws.web.bruto.itramites.agesic.gub.uy/cabezalService/persist")
    @ResponseWrapper(localName = "persistResponse", targetNamespace = "http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/cabezalService", className = "uy.gub.agesic.itramites.bruto.web.ws.cabezal.PersistResponse")
    public uy.gub.agesic.itramites.bruto.web.ws.cabezal.CabezalResponseDTO persist(
        @WebParam(name = "traza", targetNamespace = "")
        uy.gub.agesic.itramites.bruto.web.ws.cabezal.CabezalDTO traza
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/cabezalService", className = "uy.gub.agesic.itramites.bruto.web.ws.cabezal.Ping")
    @WebMethod(action = "http://ws.web.bruto.itramites.agesic.gub.uy/cabezalService/ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://ws.web.captura.trazabilidad.agesic.gub.uy/api/v2/cabezalService", className = "uy.gub.agesic.itramites.bruto.web.ws.cabezal.PingResponse")
    public java.lang.String ping();
}
