version: '3.6'
services:
  postgresql:
    image: postgres:13.7
    container_name: 'postgresql_sae4'
    volumes:
      - ./postgres_datadir:/var/lib/postgresql/data
      - ./scripts:/tmp/scripts
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: sae
      POSTGRES_PASSWORD: sae
  wildfly:
    image: jboss/wildfly:24.0.0.Final
    container_name: 'wildfly_sae4'
    volumes:
      - ./volumes/wildfly24/modules/fileupload:/opt/jboss/wildfly/modules/system/layers/base/org/apache/commons/fileupload
      - ./volumes/wildfly24/modules/postgresql:/opt/jboss/wildfly/modules/system/layers/base/org/postgresql
      - ./volumes/wildfly24/modules/iduruguay:/opt/jboss/wildfly/modules/system/layers/base/iduruguay
      - ./volumes/wildfly24/modules/sofis-loginmodule/lat/sofis/saelogin:/opt/jboss/wildfly/modules/system/layers/base/lat/sofis/saelogin
      - ./volumes/wildfly24/configuration/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
      - ./volumes/wildfly24/deployments:/opt/jboss/wildfly/standalone/deployments
      - ./volumes/wildfly24/logs:/opt/jboss/wildfly/standalone/log
    ports:
      - "18080:8080"
      - "18443:8443"
      - "18787:8787"
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787 -Duser.timezone=America/Montevideo -Xms1024M -Xmx2048M -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true -Duser.language=es -Duser.country=UY
      - DBCONNECTION_URL=jdbc:postgresql://postgresql:5432/sae
      - DBHOST=postgresql
      - BDPORT=5432
      - DBUSER=sae
      - DBPASS=sae
      - SMTPPORT=10000
      - SMTPHOST=localhost
      - SMTPUSER=sae@agesicsisinfo.gub.uy
      - SMTPPASS=Sistemas1
      - SMTPSSL=false
